version: '3.1'
services:
  nginx:
    container_name: app_nginx
    image: nginx:latest
    volumes:
     - ./nginx_conf/magento.conf:/etc/nginx/conf.d/default.conf
     # - ./nginx_conf/laravel.conf:/etc/nginx/conf.d/laravel.conf
     - ../www:/usr/share/nginx/www
    working_dir: /usr/share/nginx/www
    ports:
      - 80:80
      - 443:443
    expose:
      - 443
    links:
      # - db
      - php:app_php
    depends_on:
      - php

  php:
    container_name: app_php
    image: lima195/php-fpm7.4:stable
    user: john
    volumes:
     - ../www:/usr/share/nginx/www
     - ./etc/php_ini/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
     - './composer/auth.json:/home/john/.composer/auth.json'
     - './etc/sh/cp-files.sh:/home/john/cp-files.sh'
    working_dir: /usr/share/nginx/www

  adminer:
    container_name: app_adminer
    image: adminer
    ports:
      - 8080:8080
    links:
      - db

  db:
    container_name: app_mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: app
    ports:
      - 33066:3306

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: app_elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      # - ELASTIC_PASSWORD=app
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./volumes/elasticsearch:/usr/share/elasticsearch/data
    # command: sh -c "[ -d ./elasticsearchss ] || mkdir ./elasticsearchss"
    ports:
      - 9200:9200
      - 9300:9300