version: '3.1'
services:
  nginx:
    container_name: laravel_nginx
    image: nginx:latest
    volumes:
     - ./nginx_conf/default.conf:/etc/nginx/conf.d/default.conf
     - ../www:/usr/share/nginx/www
    working_dir: /usr/share/nginx/www
    ports:
      - 80:80
      - 443:443
    expose:
      - 443
    links:
      # - db
      - php:laravel_php
    depends_on:
      - php

  php:
    container_name: laravel_php
    image: lima195/php-fpm7.2:1.0
    user: john
    volumes:
     - ../www:/usr/share/nginx/www
     - ./etc/php_ini/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
     - ./etc/php_ini/php.ini:/usr/local/etc/php/php.ini
    working_dir: /usr/share/nginx/www

  db:
    container_name: laravel_mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./volumes/mysql/volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: app
    ports:
      - 33066:3306

  adminer:
    container_name: laravel_adminer
    image: adminer
    ports:
      - 8888:8080
    links:
      - db

  assets:
    container_name: laravel_assets
    build:
      context: .
      dockerfile: ./assets/Dockerfile
    volumes:
     - ../www:/usr/share/nginx/www
    working_dir: /usr/share/nginx/www
    tty: true
