version: '3.1'
services:
  nginx:
    container_name: app_nginx
    image: nginx:latest
    volumes:
     # - ./nginx_conf/magento.conf:/etc/nginx/conf.d/default.conf
     - ./nginx_conf/laravel.conf:/etc/nginx/conf.d/default.conf
     - ../www:/usr/share/nginx/www
    working_dir: /usr/share/nginx/www
    ports:
      - 80:80
      - 443:443
    expose:
      - 443
    links:
      - php:app_php
    depends_on:
      - php

  php:
    container_name: app_php
    image: lima195/php-fpm7.4:stable
    user: john
    environment:
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: remote_host=10.254.254.254
    volumes:
     - ../www:/usr/share/nginx/www
     - ./etc/php_ini/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
     # - './composer/auth.json:/home/john/.composer/auth.json'
     # - './etc/sh/cp-files.sh:/home/john/cp-files.sh'
    working_dir: /usr/share/nginx/www

  mysql:
    container_name: app_mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./volumes/mysql/volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: app

  adminer:
    container_name: app_adminer
    image: adminer
    ports:
      - 8888:8080
    links:
      - mysql

  # assets:
  #   container_name: app_assets
  #   build:
  #     context: .
  #     dockerfile: ./assets/Dockerfile
  #   volumes:
  #    - ../www:/usr/share/nginx/www
  #   working_dir: /usr/share/nginx/www
  #   tty: true
